# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-05-10 13:42:20
"""
import arcpy

def CheatingFinalToolbox():  # Model1

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = True

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("3D")
    arcpy.CheckOutExtension("spatial")

    ncei13_s14x00_w170x00_2021v1_tif = arcpy.Raster("C:\\Peck_NRS528_PythonGIS\\pythonProject\\Cheating\\ncei13_s14x00_w170x00_2021v1.tif")
    ncei13_s14x00_w170x25_2021v1_tif = arcpy.Raster("C:\\Peck_NRS528_PythonGIS\\pythonProject\\Cheating\\ncei13_s14x00_w170x25_2021v1.tif")
    ncei13_s14x00_w170x50_2021v1_tif = arcpy.Raster("C:\\Peck_NRS528_PythonGIS\\pythonProject\\Cheating\\ncei13_s14x00_w170x50_2021v1.tif")
    ncei13_s14x25_w170x00_2021v1_tif = arcpy.Raster("C:\\Peck_NRS528_PythonGIS\\pythonProject\\Cheating\\ncei13_s14x25_w170x00_2021v1.tif")
    ncei13_s14x25_w170x25_2021v1_tif = arcpy.Raster("C:\\Peck_NRS528_PythonGIS\\pythonProject\\Cheating\\ncei13_s14x25_w170x25_2021v1.tif")
    ncei13_s14x25_w170x50_2021v1_tif = arcpy.Raster("C:\\Peck_NRS528_PythonGIS\\pythonProject\\Cheating\\ncei13_s14x25_w170x50_2021v1.tif")
    Cheating = "C:\\Peck_NRS528_PythonGIS\\pythonProject\\Cheating"

    # Process: Mosaic To New Raster (Mosaic To New Raster) (management)
    Mosaic = arcpy.management.MosaicToNewRaster(input_rasters=[ncei13_s14x00_w170x00_2021v1_tif, ncei13_s14x00_w170x25_2021v1_tif, ncei13_s14x00_w170x50_2021v1_tif, ncei13_s14x25_w170x00_2021v1_tif, ncei13_s14x25_w170x25_2021v1_tif, ncei13_s14x25_w170x50_2021v1_tif], output_location=Cheating, raster_dataset_name_with_extension="Mosaic", coordinate_system_for_the_raster="PROJCS[\"WGS_1984_Web_Mercator_Auxiliary_Sphere\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Mercator_Auxiliary_Sphere\"],PARAMETER[\"False_Easting\",0.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",0.0],PARAMETER[\"Standard_Parallel_1\",0.0],PARAMETER[\"Auxiliary_Sphere_Type\",0.0],UNIT[\"Meter\",1.0]]", pixel_type="32_BIT_SIGNED", number_of_bands=1)[0]
    Mosaic = arcpy.Raster(Mosaic)

    # Process: Slope (Slope) (3d)
    Slope_3_ = "C:\\GeoData\\ArcProProjectFiles\\test\\test.gdb\\Slope"
    arcpy.ddd.Slope(in_raster=Mosaic, out_raster=Slope_3_, output_measurement="DEGREE")
    Slope_3_ = arcpy.Raster(Slope_3_)

    # Process: Reclassify (Reclassify) (3d)
    BathyTsunamiRiskGrades = "C:\\GeoData\\ArcProProjectFiles\\test\\test.gdb\\BathyTsunamiRiskGrades"
    arcpy.ddd.Reclassify(in_raster=Slope_3_, reclass_field="VALUE", remap="0 22.500000 1;22.500000 45 2;45 90 0", out_raster=BathyTsunamiRiskGrades)
    BathyTsunamiRiskGrades = arcpy.Raster(BathyTsunamiRiskGrades)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\GeoData\\ArcProProjectFiles\\test\\test.gdb", workspace="C:\\GeoData\\ArcProProjectFiles\\test\\test.gdb"):
        CheatingFinalToolbox()
