# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-03-04 17:52:31
"""
import arcpy

def CourseTsunamiSourcesTool():  # Course Tsunami Sources Tool

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("3D")
    arcpy.CheckOutExtension("spatial")

    arcpy.ImportToolbox(r"C:\GeoData\ArcProProjectFiles\Indonesia_Tsunami_Model\ViewshedTool\2D_Viewshed_Analysis.tbx")
    gem_active_faults_harmonized_shp = "C:\\GeoData\\ArcProProjectFiles\\Indonesia_Tsunami_Model\\InputData\\Coastline and Earthquake Scratch\\gem_active_faults_harmonized.shp"
    World_Countries_shp = "C:\\GeoData\\ArcProProjectFiles\\Indonesia_Tsunami_Model\\InputData\\Coastline and Earthquake Scratch\\World_Countries.shp"
    OutputViewshed = "C:\\GeoData\\ArcProProjectFiles\\Indonesia_Tsunami_Model\\OutputViewshed"

    # Process: Project (2) (Project) (management)
    faultLines_Project = "C:\\GeoData\\ArcProProjectFiles\\Indonesia_Tsunami_Model\\Indonesia_Tsunami_Model.gdb\\faultLines_Project"
    arcpy.management.Project(in_dataset=gem_active_faults_harmonized_shp, out_dataset=faultLines_Project, out_coor_system="PROJCS[\"DGN_1995_UTM_Zone_47N\",GEOGCS[\"GCS_DGN_1995\",DATUM[\"D_Datum_Geodesi_Nasional_1995\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",99.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]")

    # Process: Project (Project) (management)
    World_Countries_Project = "C:\\GeoData\\ArcProProjectFiles\\Indonesia_Tsunami_Model\\Indonesia_Tsunami_Model.gdb\\World_Countries_Project"
    arcpy.management.Project(in_dataset=World_Countries_shp, out_dataset=World_Countries_Project, out_coor_system="PROJCS[\"DGN_1995_UTM_Zone_47N\",GEOGCS[\"GCS_DGN_1995\",DATUM[\"D_Datum_Geodesi_Nasional_1995\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",99.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]")

    # Process: Delete Field (Delete Field) (management)
    World_Countries_Project_3_ = arcpy.management.DeleteField(in_table=World_Countries_Project, drop_field=["COUNTRY", "ISO_CC", "CONTINENT", "LAND_TYPE", "LAND_RANK", "COUNTRYAFF"])[0]

    # Process: Feature to Raster (Feature to Raster) (conversion)
    Countries = "C:\\GeoData\\ArcProProjectFiles\\Indonesia_Tsunami_Model\\Indonesia_Tsunami_Model.gdb\\Countries"
    with arcpy.EnvManager(extent="86.0700725040824 -13.37299502315 112.2219296877 11.7178082890554 GEOGCS[\"GCS_WGS_1984_Earthquakes\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],VERTCS[\"GCS_WGS_1984_Earthquakes\",VDATUM[\"WGS_1984_Geoid\"],PARAMETER[\"Vertical_Shift\",0.0],PARAMETER[\"Direction\",1.0],UNIT[\"Meter\",1.0]]"):
        arcpy.conversion.FeatureToRaster(in_features=World_Countries_Project_3_, field="OBJECTID", out_raster=Countries, cell_size="300")
        Countries = arcpy.Raster(Countries)

    # Process: Reclassify (Reclassify) (3d)
    land1_else0 = "C:\\GeoData\\ArcProProjectFiles\\Indonesia_Tsunami_Model\\Indonesia_Tsunami_Model.gdb\\land1_else0"
    arcpy.ddd.Reclassify(in_raster=Countries, reclass_field="VALUE", remap="0 1;92 1;93 1;94 1;118 1;120 1;121 1;277 1;278 1;279 1;280 1;282 1;283 1;284 1;351 1;352 1;353 1;354 1;393 1;394 1;396 1;527 1;528 1;529 1;578 1;579 1;580 1;639 1;640 1;641 1;642 1;NODATA 0", out_raster=land1_else0)
    land1_else0 = arcpy.Raster(land1_else0)

    # Process: 2D viewshed (2D viewshed) (NewToolbox)
    arcpy.NewToolbox.Script(Observation_features=faultLines_Project, Line-of-sight_barriers=land1_else0, Cell size=300, Output_workspace=OutputViewshed)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\GeoData\\ArcProProjectFiles\\Indonesia_Tsunami_Model\\Indonesia_Tsunami_Model.gdb", workspace="C:\\GeoData\\ArcProProjectFiles\\Indonesia_Tsunami_Model\\Indonesia_Tsunami_Model.gdb"):
        CourseTsunamiSourcesTool()
