# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-03-20 13:41:18
"""
import arcpy
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *
from arcpy.sa import *

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("3D")
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    SRTMvoidfilled_YardlandIrelandFlood = arcpy.Raster("C:\\GeoData\\ArcProProjectFiles\\DEM_FloodTool_PythonTemplate\\DEM_FloodTool_PythonTemplate.gdb\\SRTMvoidfilled_YardlandIrelandFlood")
    Input_false_raster_or_constant_value = 1
    Input_false_raster_or_constant_value_2_ = 1

    # Process: Set Null (Set Null) (ia)
    SeaLevel1_elseNULL = "C:\\GeoData\\ArcProProjectFiles\\DEM_FloodTool_PythonTemplate\\DEM_FloodTool_PythonTemplate.gdb\\SeaLevel1_elseNULL"
    Set_Null = SeaLevel1_elseNULL
    SeaLevel1_elseNULL = arcpy.ia.SetNull(SRTMvoidfilled_YardlandIrelandFlood, Input_false_raster_or_constant_value, "VALUE >= 1")
    SeaLevel1_elseNULL.save(Set_Null)


    # Process: Region Group (Region Group) (sa)
    SeaLevelGroups = "C:\\GeoData\\ArcProProjectFiles\\DEM_FloodTool_PythonTemplate\\DEM_FloodTool_PythonTemplate.gdb\\SeaLevelGroups"
    Region_Group = SeaLevelGroups
    SeaLevelGroups = arcpy.sa.RegionGroup(SeaLevel1_elseNULL, "FOUR", "WITHIN", "ADD_LINK", None)
    SeaLevelGroups.save(Region_Group)


    # Process: Test (2) (Test) (ia)
    Ocean1_else0 = "C:\\GeoData\\ArcProProjectFiles\\DEM_FloodTool_PythonTemplate\\DEM_FloodTool_PythonTemplate.gdb\\Ocean1_else0"
    Test_2_ = Ocean1_else0
    Ocean1_else0 = arcpy.ia.Test(SeaLevelGroups, "Count >= 50")
    Ocean1_else0.save(Test_2_)


    # Process: Set Null (2) (Set Null) (ia)
    Ocean1 = "C:\\GeoData\\ArcProProjectFiles\\DEM_FloodTool_PythonTemplate\\DEM_FloodTool_PythonTemplate.gdb\\Ocean1"
    Set_Null_2_ = Ocean1
    Ocean1 = arcpy.ia.SetNull(Ocean1_else0, Input_false_raster_or_constant_value_2_, "VALUE = 0")
    Ocean1.save(Set_Null_2_)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\GeoData\\ArcProProjectFiles\\DEM_FloodTool_PythonTemplate\\DEM_FloodTool_PythonTemplate.gdb", workspace="C:\\GeoData\\ArcProProjectFiles\\DEM_FloodTool_PythonTemplate\\DEM_FloodTool_PythonTemplate.gdb"):
        Model()
