# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-03-01 15:39:13
"""
import arcpy

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    LC08_L1TP_012031_20131212_20170307_01_T1_B1_tif = arcpy.Raster("C:\\Peck_NRS528_PythonGIS\\pythonProject\\Classes\\06_cheating\\Step_2_data\\Winter_2013\\LC08_L1TP_012031_20131212_20170307_01_T1_B1.tif")
    LC08_L1TP_012031_20131212_20170307_01_T1_B2_tif = arcpy.Raster("C:\\Peck_NRS528_PythonGIS\\pythonProject\\Classes\\06_cheating\\Step_2_data\\Winter_2013\\LC08_L1TP_012031_20131212_20170307_01_T1_B2.tif")
    LC08_L1TP_012031_20131212_20170307_01_T1_B3_tif = arcpy.Raster("C:\\Peck_NRS528_PythonGIS\\pythonProject\\Classes\\06_cheating\\Step_2_data\\Winter_2013\\LC08_L1TP_012031_20131212_20170307_01_T1_B3.tif")
    LC08_L1TP_012031_20131212_20170307_01_T1_B4_tif = arcpy.Raster("C:\\Peck_NRS528_PythonGIS\\pythonProject\\Classes\\06_cheating\\Step_2_data\\Winter_2013\\LC08_L1TP_012031_20131212_20170307_01_T1_B4.tif")
    LC08_L1TP_012031_20131212_20170307_01_T1_B5_tif = arcpy.Raster("C:\\Peck_NRS528_PythonGIS\\pythonProject\\Classes\\06_cheating\\Step_2_data\\Winter_2013\\LC08_L1TP_012031_20131212_20170307_01_T1_B5.tif")
    LC08_L1TP_012031_20131212_20170307_01_T1_B6_tif = arcpy.Raster("C:\\Peck_NRS528_PythonGIS\\pythonProject\\Classes\\06_cheating\\Step_2_data\\Winter_2013\\LC08_L1TP_012031_20131212_20170307_01_T1_B6.tif")
    LC08_L1TP_012031_20131212_20170307_01_T1_B7_tif = arcpy.Raster("C:\\Peck_NRS528_PythonGIS\\pythonProject\\Classes\\06_cheating\\Step_2_data\\Winter_2013\\LC08_L1TP_012031_20131212_20170307_01_T1_B7.tif")
    LC08_L1TP_012031_20131212_20170307_01_T1_B8_tif = arcpy.Raster("C:\\Peck_NRS528_PythonGIS\\pythonProject\\Classes\\06_cheating\\Step_2_data\\Winter_2013\\LC08_L1TP_012031_20131212_20170307_01_T1_B8.tif")
    LC08_L1TP_012031_20131212_20170307_01_T1_B9_tif = arcpy.Raster("C:\\Peck_NRS528_PythonGIS\\pythonProject\\Classes\\06_cheating\\Step_2_data\\Winter_2013\\LC08_L1TP_012031_20131212_20170307_01_T1_B9.tif")
    LC08_L1TP_012031_20131212_20170307_01_T1_B10_tif = arcpy.Raster("C:\\Peck_NRS528_PythonGIS\\pythonProject\\Classes\\06_cheating\\Step_2_data\\Winter_2013\\LC08_L1TP_012031_20131212_20170307_01_T1_B10.tif")
    LC08_L1TP_012031_20131212_20170307_01_T1_B11_tif = arcpy.Raster("C:\\Peck_NRS528_PythonGIS\\pythonProject\\Classes\\06_cheating\\Step_2_data\\Winter_2013\\LC08_L1TP_012031_20131212_20170307_01_T1_B11.tif")

    # Process: Composite Bands (Composite Bands) (management)
    winter_2013_tif = "C:\\Peck_NRS528_PythonGIS\\pythonProject\\Classes\\06_cheating\\Step_2_data\\winter_2013.tif"
    arcpy.management.CompositeBands(in_rasters=[LC08_L1TP_012031_20131212_20170307_01_T1_B1_tif, LC08_L1TP_012031_20131212_20170307_01_T1_B2_tif, LC08_L1TP_012031_20131212_20170307_01_T1_B3_tif, LC08_L1TP_012031_20131212_20170307_01_T1_B4_tif, LC08_L1TP_012031_20131212_20170307_01_T1_B5_tif, LC08_L1TP_012031_20131212_20170307_01_T1_B6_tif, LC08_L1TP_012031_20131212_20170307_01_T1_B7_tif, LC08_L1TP_012031_20131212_20170307_01_T1_B8_tif, LC08_L1TP_012031_20131212_20170307_01_T1_B9_tif, LC08_L1TP_012031_20131212_20170307_01_T1_B10_tif, LC08_L1TP_012031_20131212_20170307_01_T1_B11_tif], out_raster=winter_2013_tif)
    winter_2013_tif = arcpy.Raster(winter_2013_tif)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\GeoData\\ArcProProjectFiles\\test\\test.gdb", workspace="C:\\GeoData\\ArcProProjectFiles\\test\\test.gdb"):
        Model()
